### PR TITLE
Add support for comments

### PR DESCRIPTION
**Pull request by whitneyit**
Added support for comments via [strip-json-comments](https://github.com/sindresorhus/strip-json-comments) as well as fixing a few typos :smile:

### CODE REVIEW

**Comment by whitneyit** [comment]
This is constantly breakiing on `io.js` not sure why.

**Comment by whitneyit** [comment]
Looks like the breakage was due to a difference in the `Buffer` api.

**Comment by rogeriopvl** [comment]
Stripping comments from json files is not gulp-jsonlint responsibility. It should be done in a separate gulp  plugin and executed before piping to gulp-jsonlint.

There's already a gulp plugin that you can use for this: https://www.npmjs.com/package/gulp-strip-json-comments

So you could do something like:

```javascript
var gulp = require('gulp');
var jsonlint = require('gulp-jsonlint');
var stripJsonComments = require('gulp-strip-json-comments');
 
gulp.task('default', function () {
    return gulp.src('src/config.json')
        .pipe(stripJsonComments())
        .pipe(jsonlint())
        .pipe(gulp.dest('dist'));
});
```

**Comment by rogeriopvl** [comment]
I'll gladly accept those fixed typos as a separate PR :+1:

**Comment by whitneyit** [comment]
The comments are not being stripped. It just allows a file that contains comments to be linted.

**Comment by rogeriopvl** [comment]
I see. But I mean, in my opinion this option should be provided by jsonlint itself, and not a gulp wrapper plugin. What do you think?

What use cases do you have for this?

**Comment by whitneyit** [comment]
Ok. I'll send a PR there to add the support. Then will you be open to
adding the option?

There was a good comment that I removed that said to add comments 😜

**Pull request closed without merging**
